matrix:
  include:
    - before_script:
        - "npm install --global yarn postcss postcss-cli"
      language: node
      node: 12.21.0
      script: yarn
    - before_script:
        - "pip install -r requirements.txt"
        - "export FLASK_APP=$TRAVIS_BUILD_DIR"
        - "export FLASK_ENV=production"
        - "export NODE_ENV=production"
        - "export SECRET=DQ8RwPU2NIv1st0F"
        - "export APP_SETTINGS=config.TestingConfig"
        - "export OXFORD_APP_ID=fd0f1799"
        - "export OXFORD_APP_KEY=b07f95f839de63b54d400c2f023658d3"
        - "export CODECOV_TOKEN=2b2b0d17-7fae-4cfe-88ae-cabc92a86526"
      cache: pip
      language: python
      python: 3.8
      script: pytest --cov # run tests
    - after_success:
      language: shell
      script: bash <(curl -s https://codecov.io/bash) # submit coverage
sudo: required
