dist: bionic
sudo: required
language: python
python: 3.8
before_script:
  - "nvm install 12.21.0"
  - "npm install --global yarn postcss postcss-cli"
  - "yarn"
  - "pip install -r requirements.txt"
  - "export FLASK_APP=app"
  - "export FLASK_ENV=production"
  - "export NODE_ENV=production"
  - "export SECRET=wPU7TIv1stDQ8R0F"
  - "export APP_SETTINGS=config.TestingConfig"
cache: pip
script: pytest --cov
after_success:
  - bash <(curl -s https://codecov.io/bash) # submit coverage
